author:
  name: Rahul Kulkarni
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
theme: minima
header_pages:
  - about.me
minima:
  skin: dark
