title: Rahul Kulkarni
author:
  name: Rahul Kulkarni
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true

include:
  - README.md

# theme: minima
remote_theme: jekyll/minima

minima:
  skin: dark

header_pages:
  - about.me
